blank_issues_enabled: false
contact_links:
  - name: Questions / ideas
    url: https://github.com/dudarev/append-review-v1/discussions
    about: Please use Discussions for open-ended questions and ideas.

